version: '3.3'

volumes:
  static:
  backend_static:
  backend_media:
  postgres_data:
    
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    image: tivago/foodgram_backend:latest
    env_file: .env
    volumes:
      - backend_static:/app/static
      - backend_media:/app/media
    depends_on:
      - db

  frontend:
    env_file: .env
    image: tivago/foodgram_frontend:latest
    volumes:
      - static:/app/result_build/build
    depends_on:
      - backend
      
  gateway:
    image: tivago/foodgram_gateway
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html/
      - backend_static:/backend_static
      - backend_media:/backend_media
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
