version: '3.3'

volumes:
  static:
  backend_static:
  backend_media:
  postgres_data:

services:

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env

  backend:
    build: ./backend/
    volumes:
      - backend_static:/app/static
      - backend_media:/app/media
    env_file: .env
    depends_on:
      - db

  frontend:
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/app/result_build/build
    env_file: .env
    depends_on:
      - backend

  gateway:
    build: ./infra/
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html/
      - backend_static:/backend_static
      - backend_media:/backend_media
      - ../docs/:/usr/share/nginx/html/api/docs/
    env_file: .env
    ports:
      - 8000:80
    depends_on:
      - frontend