version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: tivago/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    image: tivago/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    env_file: .env
    depends_on:
      - backend

  nginx:
    image: tivago/foodgram_infra
    volumes:
      - static:/staticfiles/
      - media:/app/media
    env_file: .env
    ports:
      - 8000:80
    depends_on:
      - frontend