version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env

  backend:
    build: ./backend/
    volumes:
      - static:/backend_static
      - media:/app/media
    env_file: .env
    depends_on:
      - db

  frontend:
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    env_file: .env
    depends_on:
      - backend

  gateway:
    build: ./infra/
    volumes:
      - static:/staticfiles/
      - media:/app/media
    env_file: .env
    ports:
      - 8000:80
    depends_on:
      - frontend