version: '3.5'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres
    env_file:
      - ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    build: ../backend/
    restart: always
    volumes:
     - static:/static/
     - media:/app/media/
    depends_on:
      - db
    env_file:
      - ../.env

  frontend:
    build: ../backend/
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    build: ./
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static/
      - media:/app/media/
    depends_on:
      - backend